### ISSUE TITLE
Is this work with newest multiwii protocol?

### ISSUE THREAD

**Issue by limhyon** [treymarc/multiwii-mavlink-gc#1]
Is this work with newest multiwii protocol?
I'm using multiwii configurator 2.3, but current code is not working with my multiwii.
Can you check?

**Comment by treymarc** [comment]
hi,

i have updated the code , tested with mwi 2.3 and latest qgs , 

https://github.com/treymarc/multiwii-mavlink-gc/blob/master/doc/img/2013-12-14-qgs-2.0.0.png
