### ISSUE TITLE
serialport.c fatal error

### ISSUE THREAD

**Issue by rharrell-southern** [treymarc/multiwii-mavlink-gc#13]
I'm getting an error on #include <termios.h> saying the file doesn't exist.  This is with the latest MinGW32 on Win7 64.  Any ideas?

**Comment by treymarc** [comment]
could you try with https://github.com/treymarc/multiwii-mavlink-gc/commit/da346abedcc2621448facc1548739eea9df968b4

**Comment by rharrell-southern** [comment]
Seems to only have built the content in the example directory. There are no .exe files in mwgc or the other directories. It says it completed though.

**Comment by treymarc** [comment]
this is fixed now  .. you can rename the mwgc-1.0  wih .exe
