### ISSUE TITLE
Add version number

### ISSUE THREAD

**Issue by koenkooi** [treymarc/multiwii-mavlink-gc#9]
I'm packaging multiwii-mavlink-gc and I noticed it lacks a version number. It's completely cosmetic, but it would be great if the readme or makefile had some form of version number (0.1, v2014.04, 2.3 etc).

**Comment by treymarc** [comment]
https://github.com/treymarc/multiwii-mavlink-gc/commit/87add1e154fc17c4066a0b5b3c335536bd7fb799
